{
 "title": "Default Dashboard",
 "tags": [ "rayVersion:2.54.0" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "SessionName",
    "query": "label_values(ray_node_network_receive_speed{}, SessionName)"
   },
   {
    "name": "Instance",
    "query": "label_values(ray_node_network_receive_speed{SessionName=~\"$SessionName\",}, instance)"
   },
   {
    "name": "Cluster",
    "query": "label_values(ray_node_network_receive_speed{}, ray_io_cluster)"
   },
   { "name": "RayNodeType", "query": "head, worker" }
  ]
 },
 "panels": [
  { "title": "Overview and Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Count",
   "type": "graph",
   "description": "Note: not impacted by \"Instance\" variable.\n\nA total number of active failed, and pending nodes from the cluster. \n\nACTIVE: A node is alive and available.\n\nFAILED: A node is dead and not available. The node is considered dead when the raylet process on the node is terminated. The node will get into the failed state if it cannot be provided (e.g., there's no available node from the cloud provider) or failed to setup (e.g., setup_commands have errors). \n\nPending: A node is being started by the Ray cluster launcher. The node is unavailable now because it is being provisioned and initialized.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "yaxes": [
    { "format": "nodes" }
   ],
   "targets": [
    {
     "expr": "sum(autoscaler_active_nodes{SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (NodeType)",
     "legendFormat": "Active Nodes: {{NodeType}}"
    },
    {
     "expr": "sum(autoscaler_recently_failed_nodes{SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (NodeType)",
     "legendFormat": "Failed Nodes: {{NodeType}}"
    },
    {
     "expr": "sum(autoscaler_pending_nodes{SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (NodeType)",
     "legendFormat": "Pending Nodes: {{NodeType}}"
    }
   ]
  },
  {
   "title": "Cluster Utilization",
   "type": "graph",
   "description": "Aggregated utilization of all physical resources (CPU, GPU, memory, disk, or etc.) across the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "avg(ray_node_cpu_utilization{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"})",
     "legendFormat": "CPU (physical)"
    },
    {
     "expr": "sum(ray_node_gpus_utilization{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) / on() (sum(ray_node_gpus_available{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) or vector(0))",
     "legendFormat": "GPU (physical)"
    },
    {
     "expr": "sum(ray_node_mem_used{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) / on() (sum(ray_node_mem_total{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"})) * 100",
     "legendFormat": "Memory (RAM)"
    },
    {
     "expr": "sum(ray_node_gram_used{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) / on() (sum(ray_node_gram_available{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) + sum(ray_node_gram_used{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"})) * 100",
     "legendFormat": "GRAM"
    },
    {
     "expr": "sum(ray_object_store_memory{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) / on() sum(ray_resources{Name=\"object_store_memory\",instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) * 100",
     "legendFormat": "Object Store Memory"
    },
    {
     "expr": "sum(ray_node_disk_usage{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) / on() (sum(ray_node_disk_free{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) + sum(ray_node_disk_usage{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"})) * 100",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Ray OOM Kills (Tasks and Actors)",
   "type": "graph",
   "description": "The number of tasks and actors killed by the Ray Out of Memory killer due to high memory pressure. Metrics are broken down by IP and the name. https://docs.ray.io/en/master/ray-core/scheduling/ray-oom-prevention.html. Note: The RayNodeType filter does not work on this graph.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "failures" } },
   "yaxes": [
    { "format": "failures" }
   ],
   "targets": [
    {
     "expr": "sum(ray_memory_manager_worker_eviction_total{instance=~\"$Instance\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (Name, instance)",
     "legendFormat": "OOM Killed: {{Name}}, {{instance}}"
    }
   ]
  },
  { "title": "Hardware Utilization by Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "description": "The physical (hardware) CPU usage for each node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(ray_node_cpu_utilization{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"} * ray_node_cpu_count{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"} / 100) by (instance, RayNodeType)",
     "legendFormat": "CPU Usage: {{instance}} ({{RayNodeType}})"
    },
    {
     "expr": "sum(ray_node_cpu_count{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node CPU Usage %",
   "type": "graph",
   "description": "The percentage of physical (hardware) CPU usage for each node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "sum(ray_node_cpu_utilization{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, RayNodeType)",
     "legendFormat": "CPU Usage: {{instance}} ({{RayNodeType}})"
    }
   ]
  },
  {
   "title": "Node Memory Usage (heap + object store)",
   "type": "graph",
   "description": "The physical (hardware) memory usage for each node. The dotted line means the total amount of memory from the cluster. Node memory is a sum of object store memory (shared memory) and heap memory.\n\nNote: If Ray is deployed within a container, the total memory could be lower than the host machine because Ray may reserve some additional memory space outside the container.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_node_mem_used{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, RayNodeType)",
     "legendFormat": "Memory Used: {{instance}} ({{RayNodeType}})"
    },
    {
     "expr": "sum(ray_node_mem_total{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node Memory Usage % (heap + object store)",
   "type": "graph",
   "description": "The percentage of physical (hardware) memory usage for each node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "sum(ray_node_mem_used{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, RayNodeType) * 100 / sum(ray_node_mem_total{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, RayNodeType)",
     "legendFormat": "Memory Used: {{instance}} ({{RayNodeType}})"
    }
   ]
  },
  {
   "title": "Node Disk Usage",
   "type": "graph",
   "description": "Node's physical (hardware) disk usage. The dotted line means the total amount of disk space from the cluster.\n\nNOTE: When Ray is deployed within a container, this shows the disk usage from the host machine. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_node_disk_usage{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, RayNodeType)",
     "legendFormat": "Disk Used: {{instance}} ({{RayNodeType}})"
    },
    {
     "expr": "sum(ray_node_disk_free{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) + sum(ray_node_disk_usage{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node Disk Usage %",
   "type": "graph",
   "description": "Node's physical (hardware) disk usage. \n\nNOTE: When Ray is deployed within a container, this shows the disk usage from the host machine. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "sum(ray_node_disk_usage{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, RayNodeType) * 100 / (sum(ray_node_disk_free{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, RayNodeType) + sum(ray_node_disk_usage{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, RayNodeType))",
     "legendFormat": "Disk Used: {{instance}} ({{RayNodeType}})"
    }
   ]
  },
  {
   "title": "Node GPU Usage",
   "type": "graph",
   "description": "Node's physical (hardware) GPU usage. The dotted line means the total number of hardware GPUs from the cluster. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "yaxes": [
    { "format": "GPUs" }
   ],
   "targets": [
    {
     "expr": "sum(ray_node_gpus_utilization{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"} / 100) by (instance, RayNodeType, GpuIndex, GpuDeviceName)",
     "legendFormat": "GPU Usage: {{instance}} ({{RayNodeType}}), gpu.{{GpuIndex}}, {{GpuDeviceName}}"
    },
    {
     "expr": "sum(ray_node_gpus_available{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node GPU Usage %",
   "type": "graph",
   "description": "Node's physical (hardware) GPU usage.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "sum(ray_node_gpus_utilization{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, RayNodeType, GpuIndex, GpuDeviceName)",
     "legendFormat": "GPU Usage: {{instance}} ({{RayNodeType}}), gpu.{{GpuIndex}}, {{GpuDeviceName}}"
    }
   ]
  },
  {
   "title": "Node GPU Memory Usage (GRAM)",
   "type": "graph",
   "description": "The physical (hardware) GPU memory usage for each node. The dotted line means the total amount of GPU memory from the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_node_gram_used{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"} * 1024 * 1024) by (instance, RayNodeType, GpuIndex, GpuDeviceName)",
     "legendFormat": "Used GRAM: {{instance}} ({{RayNodeType}}), gpu.{{GpuIndex}}, {{GpuDeviceName}}"
    },
    {
     "expr": "(sum(ray_node_gram_available{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) + sum(ray_node_gram_used{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"})) * 1024 * 1024",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node GPU Memory Usage (GRAM) %",
   "type": "graph",
   "description": "The percentage of physical (hardware) GPU memory usage for each node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "sum(ray_node_gram_used{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, RayNodeType, GpuIndex, GpuDeviceName) * 100 / (sum(ray_node_gram_available{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, RayNodeType, GpuIndex, GpuDeviceName) + sum(ray_node_gram_used{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, RayNodeType, GpuIndex, GpuDeviceName))",
     "legendFormat": "Used GRAM: {{instance}} ({{RayNodeType}}), gpu.{{GpuIndex}}, {{GpuDeviceName}}"
    }
   ]
  },
  {
   "title": "Node Disk IO Speed",
   "type": "graph",
   "description": "Disk IO per node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(ray_node_disk_io_write_speed{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, RayNodeType)",
     "legendFormat": "Write: {{instance}} ({{RayNodeType}})"
    },
    {
     "expr": "sum(ray_node_disk_io_read_speed{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, RayNodeType)",
     "legendFormat": "Read: {{instance}} ({{RayNodeType}})"
    }
   ]
  },
  {
   "title": "Node Network",
   "type": "graph",
   "description": "Network speed per node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(ray_node_network_receive_speed{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, RayNodeType)",
     "legendFormat": "Recv: {{instance}} ({{RayNodeType}})"
    },
    {
     "expr": "sum(ray_node_network_send_speed{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, RayNodeType)",
     "legendFormat": "Send: {{instance}} ({{RayNodeType}})"
    }
   ]
  },
  {
   "title": "Hardware Utilization by Ray Component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 }
  },
  {
   "title": "Node CPU Usage by Component",
   "type": "graph",
   "description": "The physical (hardware) CPU usage across the cluster, broken down by component. This reports the summed CPU usage per Ray component. Ray components consist of system components (e.g., raylet, gcs, dashboard, or agent) and the process (that contains method names) names of running tasks/actors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(ray_component_cpu_percentage{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (Component) / 100",
     "legendFormat": "{{Component}}"
    },
    {
     "expr": "sum(ray_node_cpu_count{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node Memory Usage by Component",
   "type": "graph",
   "description": "The physical (hardware) memory usage across the cluster, broken down by component. This reports the summed RSS-SHM per Ray component, which corresponds to an approximate memory usage per proc. Ray components consist of system components (e.g., raylet, gcs, dashboard, or agent) and the process (that contains method names) names of running tasks/actors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(sum(ray_component_rss_mb{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"} * 1024 * 1024) by (Component)) - (sum(ray_component_mem_shared_bytes{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (Component))",
     "legendFormat": "{{Component}}"
    },
    {
     "expr": "sum(ray_node_mem_shared_bytes{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"})",
     "legendFormat": "shared_memory"
    },
    {
     "expr": "sum(ray_node_mem_total{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node GPU Usage by Component",
   "type": "graph",
   "description": "The physical (hardware) GPU usage across the cluster, broken down by component. This reports the summed GPU usage per Ray component.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "yaxes": [
    { "format": "GPUs" }
   ],
   "targets": [
    {
     "expr": "sum(ray_component_gpu_percentage{SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"} / 100) by (Component)",
     "legendFormat": "{{Component}}"
    }
   ]
  },
  {
   "title": "Node GPU Memory Usage by Component",
   "type": "graph",
   "description": "The physical (hardware) GPU memory usage across the cluster, broken down by component. This reports the summed GPU memory usage per Ray component.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_component_gpu_memory_mb{SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"} * 1024 * 1024) by (Component)",
     "legendFormat": "{{Component}}"
    },
    {
     "expr": "(sum(ray_node_gram_available{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) + sum(ray_node_gram_used{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"})) * 1024 * 1024",
     "legendFormat": "MAX"
    }
   ]
  },
  { "title": "Ray Resources by Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Logical CPUs Usage",
   "type": "graph",
   "description": "Logical CPU usage of Ray. The dotted line indicates the total number of CPUs. The logical CPU is allocated by `num_cpus` arguments from tasks and actors. PENDING means the number of CPUs that will be available when new nodes are up after the autoscaler scales up.\n\nNOTE: Ray's logical CPU is different from physical CPU usage. Ray's logical CPU is allocated by `num_cpus` arguments.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(ray_resources{Name=\"CPU\",State=\"USED\",instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance)",
     "legendFormat": "CPU Usage: {{instance}}"
    },
    {
     "expr": "sum(ray_resources{Name=\"CPU\",instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"})",
     "legendFormat": "MAX"
    },
    {
     "expr": "((sum(autoscaler_cluster_resources{resource=\"CPU\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) or vector(0)) + (sum(autoscaler_pending_resources{resource=\"CPU\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) or vector(0)) and (sum(autoscaler_cluster_resources{resource=\"CPU\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) or vector(0)) + (sum(autoscaler_pending_resources{resource=\"CPU\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) or vector(0)) > (sum(autoscaler_cluster_resources{resource=\"CPU\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) or vector(0)))",
     "legendFormat": "MAX + PENDING"
    }
   ]
  },
  {
   "title": "Logical GPUs Usage",
   "type": "graph",
   "description": "Logical GPU usage of Ray. The dotted line indicates the total number of GPUs. The logical GPU is allocated by `num_gpus` arguments from tasks and actors. PENDING means the number of GPUs that will be available when new nodes are up after the autoscaler scales up.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "yaxes": [
    { "format": "GPUs" }
   ],
   "targets": [
    {
     "expr": "sum(ray_resources{Name=\"GPU\",State=\"USED\",instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance)",
     "legendFormat": "GPU Usage: {{instance}}"
    },
    {
     "expr": "sum(ray_resources{Name=\"GPU\",instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"})",
     "legendFormat": "MAX"
    },
    {
     "expr": "((sum(autoscaler_cluster_resources{resource=\"GPU\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) or vector(0)) + (sum(autoscaler_pending_resources{resource=\"GPU\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) or vector(0)) and (sum(autoscaler_cluster_resources{resource=\"GPU\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) or vector(0)) + (sum(autoscaler_pending_resources{resource=\"GPU\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) or vector(0)) > (sum(autoscaler_cluster_resources{resource=\"GPU\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) or vector(0)))",
     "legendFormat": "MAX + PENDING"
    }
   ]
  },
  {
   "title": "Object Store Memory Usage",
   "type": "graph",
   "description": "Object store memory usage by instance, including memory that has been spilled to disk. The dotted line indicates the object store memory capacity. This metric can go over the max capacity in case of spillage to disk.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_object_store_memory{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(ray_resources{Name=\"object_store_memory\",instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Object Store Memory Usage %",
   "type": "graph",
   "description": "Object store memory usage % by instance, including memory that has been spilled to disk. This metric can go over 100% in case of spillage to disk.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "sum(ray_object_store_memory{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance) * 100 / sum(ray_resources{Name=\"object_store_memory\",instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    { "expr": "100", "legendFormat": "MAX" }
   ]
  },
  {
   "title": "Object Store Memory Spilled to Disk",
   "type": "graph",
   "description": "Object store memory that has been spilled to disk, by instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_object_store_memory{instance=~\"$Instance\",Location=\"SPILLED\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ray Tasks, Actors and Placement Groups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 }
  },
  {
   "title": "All Tasks by State",
   "type": "graph",
   "description": "Current count of tasks, grouped by scheduler state (e.g., pending, running, finished).\n\nState: the task state, as described by rpc::TaskStatus proto in common.proto. Task resubmissions due to failures or object reconstruction are shown with (retry) in the label.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "tasks" } },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(ray_tasks{IsRetry=\"0\",State=~\"FINISHED|FAILED\",instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}[14d])) by (State) or clamp_min(sum(ray_tasks{IsRetry=\"0\",State!~\"FINISHED|FAILED\",instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (State), 0)",
     "legendFormat": "{{State}}"
    },
    {
     "expr": "sum(max_over_time(ray_tasks{IsRetry!=\"0\",State=~\"FINISHED|FAILED\",instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}[14d])) by (State) or clamp_min(sum(ray_tasks{IsRetry!=\"0\",State!~\"FINISHED|FAILED\",instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (State), 0)",
     "legendFormat": "{{State}} (retry)"
    }
   ]
  },
  {
   "title": "Active Tasks by Name",
   "type": "graph",
   "description": "Current count of active tasks (i.e. pending or running; not finished), grouped by task name. Task resubmissions due to failures or object reconstruction are shown with (retry) in the label.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "tasks" } },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "clamp_min(sum(ray_tasks{IsRetry=\"0\",State!~\"FINISHED|FAILED\",instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (Name), 0)",
     "legendFormat": "{{Name}}"
    },
    {
     "expr": "clamp_min(sum(ray_tasks{IsRetry!=\"0\",State!~\"FINISHED|FAILED\",instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (Name), 0)",
     "legendFormat": "{{Name}} (retry)"
    }
   ]
  },
  {
   "title": "Running Tasks by Name",
   "type": "graph",
   "description": "Current count of tasks that are currently executing, grouped by task name. Task resubmissions due to failures or object reconstruction are shown with (retry) in the label.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "tasks" } },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "clamp_min(sum(ray_tasks{IsRetry=\"0\",State=~\"RUNNING*\",instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (Name), 0)",
     "legendFormat": "{{Name}}"
    },
    {
     "expr": "clamp_min(sum(ray_tasks{IsRetry!=\"0\",State=~\"RUNNING*\",instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (Name), 0)",
     "legendFormat": "{{Name}} (retry)"
    }
   ]
  },
  {
   "title": "All Actors by State",
   "type": "graph",
   "description": "Note: not impacted by \"Instance\" variable.\n\nCurrent count of actors, grouped by lifecycle state (e.g., alive, restarting, dead/terminated).\n\nState: the actor state, as described by rpc::ActorTableData proto in gcs.proto.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "actors" } },
   "yaxes": [
    { "format": "actors" }
   ],
   "targets": [
    {
     "expr": "sum(ray_actors{Source=\"gcs\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (State)",
     "legendFormat": "{{State}}"
    }
   ]
  },
  {
   "title": "Alive Actors by State",
   "type": "graph",
   "description": "Current count of alive actors (i.e. not dead/terminated), grouped by state.\n\nState: the actor state, as described by rpc::ActorTableData proto in gcs.proto.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "actors" } },
   "yaxes": [
    { "format": "actors" }
   ],
   "targets": [
    {
     "expr": "sum(ray_actors{Source=\"executor\",NodeAddress=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (State)",
     "legendFormat": "{{State}}"
    }
   ]
  },
  {
   "title": "Alive Actors by Name",
   "type": "graph",
   "description": "Current count of alive actors, grouped by actor name.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "actors" } },
   "yaxes": [
    { "format": "actors" }
   ],
   "targets": [
    {
     "expr": "sum(ray_actors{State!=\"DEAD\",Source=\"executor\",NodeAddress=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (Name)",
     "legendFormat": "{{Name}}"
    }
   ]
  },
  {
   "title": "All Placement Groups by State",
   "type": "graph",
   "description": "Note: not impacted by \"Instance\" variable.\n\nCurrent count of placement groups, grouped by state.\n\nState: the placement group state, as described by the rpc::PlacementGroupTableData proto in gcs.proto.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "placement groups" } },
   "yaxes": [
    { "format": "placement groups" }
   ],
   "targets": [
    {
     "expr": "sum(ray_placement_groups{SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (State)",
     "legendFormat": "{{State}}"
    }
   ]
  },
  {
   "title": "Object Store Memory by Location",
   "type": "graph",
   "description": "Object store memory usage by location. The dotted line indicates the object store memory capacity. This metric can go over the max capacity in case of spillage to disk.\n\nLocation: where the memory was allocated, which is MMAP_SHM or MMAP_DISK to indicate memory-mapped page, SPILLED to indicate spillage to disk, and WORKER_HEAP for objects small enough to be inlined in worker memory.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_object_store_memory{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (Location)",
     "legendFormat": "{{Location}}"
    },
    {
     "expr": "sum(ray_resources{Name=\"object_store_memory\",instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "TPU Utilization by Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node TPU Tensorcore Utilization %",
     "type": "graph",
     "description": "Percentage of tensorcore utilization for the TPUs on this node. Computed by dividing the number of tensorcore operations by the maximum supported number of operations during the sample period.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "yaxes": [
      { "format": "%" }
     ],
     "targets": [
      {
       "expr": "sum(ray_tpu_tensorcore_utilization{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, TpuIndex, TpuDeviceName, TpuType, TpuTopology)",
       "legendFormat": "{{instance}}, tpu.{{TpuIndex}}, {{TpuType}}, {{TpuTopology}}"
      }
     ]
    },
    {
     "title": "Node TPU High Bandwidth Memory Utilization %",
     "type": "graph",
     "description": "Percentage of bandwidth memory utilization for the TPUs on this node. Computed by dividing the memory bandwidth used by the maximum supported memory bandwidth limit during the sample period.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "yaxes": [
      { "format": "%" }
     ],
     "targets": [
      {
       "expr": "sum(ray_tpu_memory_bandwidth_utilization{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, TpuIndex, TpuDeviceName, TpuType, TpuTopology)",
       "legendFormat": "{{instance}}, tpu.{{TpuIndex}}, {{TpuType}}, {{TpuTopology}}"
      }
     ]
    },
    {
     "title": "Node TPU Duty Cycle %",
     "type": "graph",
     "description": "Percentage of time over the sample period during which the TPU is actively processing.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "yaxes": [
      { "format": "%" }
     ],
     "targets": [
      {
       "expr": "sum(ray_tpu_duty_cycle{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, TpuIndex, TpuDeviceName, TpuType, TpuTopology) or vector(0)",
       "legendFormat": "{{instance}}, tpu.{{TpuIndex}}, {{TpuType}}, {{TpuTopology}}"
      }
     ]
    },
    {
     "title": "Node TPU Memory Used",
     "type": "graph",
     "description": "Total memory used/allocated for the TPUs on this node.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(ray_tpu_memory_used{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, TpuIndex, TpuDeviceName, TpuType, TpuTopology) or vector(0)",
       "legendFormat": "Memory Used: {{instance}}, tpu.{{TpuIndex}}, {{TpuType}}, {{TpuTopology}}"
      },
      {
       "expr": "sum(ray_tpu_memory_total{instance=~\"$Instance\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\"}) by (instance, TpuIndex, TpuDeviceName, TpuType, TpuTopology) or vector(0)",
       "legendFormat": "Memory Total: {{instance}}, tpu.{{TpuIndex}}, {{TpuType}}, {{TpuTopology}}"
      }
     ]
    }
   ]
  }
 ]
}